AWSTemplateFormatVersion: '2010-09-09'
Description: Builds a DynamoDB table.
Resources:
  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Products'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
